version: '3.4'

services:
  dncytemplate.api:
    image: ${DOCKER_REGISTRY-}dncytemplateapi
    build:
      context: .
      dockerfile: ./DncyTemplate.Entry/DncyTemplate.Api/Dockerfile

  dncytemplate.mvc:
    image: ${DOCKER_REGISTRY-}dncytemplatemvc
    build:
      context: .
      dockerfile: ./DncyTemplate.Entry/DncyTemplate.Mvc/Dockerfile

  dncytemplate.job:
    image: ${DOCKER_REGISTRY-}dncytemplatejob
    build:
      context: .
      dockerfile: ./DncyTemplate.Job/Dockerfile

